<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <title>Borrowing Report - UB Library</title>
    <style>
        @page {
            size: A4 portrait;
            margin: 15mm 15mm 20mm 15mm;
        }

        body {
            font-family: 'Helvetica', 'Arial', sans-serif;
            color: #333;
            font-size: 9pt;
            line-height: 1.4;
            background: #fff;
        }

        .header-container {
            border-bottom: 2px solid #333;
            padding-bottom: 5px;
            margin-bottom: 15px;
            text-align: center;
        }

        .header-title {
            font-size: 16pt;
            font-weight: bold;
            text-transform: uppercase;
            margin: 0;
            color: #111;
        }

        .header-subtitle {
            font-size: 11pt;
            margin: 3px 0 0 0;
            color: #666;
        }

        .report-title {
            font-size: 12pt;
            font-weight: bold;
            margin-top: 10px;
            text-align: center;
            text-transform: uppercase;
        }

        .meta-info-table {
            width: 100%;
            margin-bottom: 15px;
            border-collapse: collapse;
        }

        .meta-info-table td {
            padding: 2px 0;
            border: none;
            font-size: 8.5pt;
        }

        .report-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
            font-size: 8.5pt;
        }

        .report-table th, .report-table td {
            border: 0.5px solid #666;
            padding: 6px 8px;
            text-align: left;
        }

        .report-table th {
            background-color: #f0f0f0;
            font-weight: bold;
            text-transform: uppercase;
        }

        .footer-container {
            position: fixed;
            bottom: -10mm;
            left: 0;
            right: 0;
            height: 10mm;
            border-top: 0.5px solid #ccc;
            padding-top: 5px;
            font-size: 7.5pt;
            text-align: center;
            color: #666;
        }

        /* Page Numbering in DomPDF */
        .page-number:before {
            content: counter(page);
        }
        .page-count:before {
            content: counter(pages);
        }
    </style>
</head>
<body>

    <!-- Library Header -->
    <div class="header-container">
        <h1 class="header-title">UB Library</h1>
        <div class="header-subtitle">Library Management System</div>
    </div>

    <div class="report-title">LAPORAN PEMINJAMAN BUKU</div>

    <!-- Report Info -->
    <table class="meta-info-table">
        <tr>
            <td style="width: 18%;"><strong>Generated Date:</strong></td>
            <td style="width: 32%;">{{ now()->translatedFormat('d F Y H:i') }}</td>
            <td style="width: 18%; text-align: right;"><strong>Generated By:</strong></td>
            <td style="width: 32%; text-align: right;">{{ $generatedBy }}</td>
        </tr>
        <tr>
            <td><strong>Selected Date Range:</strong></td>
            <td>{{ $dateRange }}</td>
            <td style="text-align: right;"><strong>Total Records:</strong></td>
            <td style="text-align: right;">{{ $records->count() }}</td>
        </tr>
    </table>

    <!-- Report Table -->
    <table class="report-table">
        <thead>
            <tr>
                <th style="width: 5%;">No.</th>
                <th style="width: 35%;">Book Title</th>
                <th style="width: 20%;">Member</th>
                <th style="width: 11%;">Borrow Date</th>
                <th style="width: 11%;">Due Date</th>
                <th style="width: 11%;">Return Date</th>
                <th style="width: 7%;">Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($records as $index => $record)
                @php
                    $member = \App\Models\Member::where('email', $record->user->email)->first();
                @endphp
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td><strong>{{ $record->book->judul ?? 'Buku Dihapus' }}</strong></td>
                    <td>{{ $record->user->name ?? 'User' }} ({{ $member->kode_anggota ?? '-' }})</td>
                    <td>{{ \Carbon\Carbon::parse($record->borrow_date)->translatedFormat('d M Y') }}</td>
                    <td>{{ \Carbon\Carbon::parse($record->due_date)->translatedFormat('d M Y') }}</td>
                    <td>
                        @if($record->return_date)
                            {{ \Carbon\Carbon::parse($record->return_date)->translatedFormat('d M Y') }}
                        @else
                            -
                        @endif
                    </td>
                    <td>
                        {{ $record->displayStatus() }}
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <!-- Footer -->
    <div class="footer-container">
        Total Records: {{ $records->count() }} | Generated automatically by UB Library System | Page <span class="page-number"></span> of <span class="page-count"></span>
    </div>

</body>
</html>
