<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Borrowing Report - UB Library</title>
    <!-- Bootstrap CSS for basic grid and layout elements -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            background-color: white !important;
            color: black !important;
            font-family: 'Times New Roman', Times, serif;
            font-size: 12pt;
            line-height: 1.5;
            padding: 20px;
        }

        .header-container {
            border-bottom: 3px double black;
            padding-bottom: 10px;
            margin-bottom: 20px;
            text-align: center;
        }

        .header-title {
            font-size: 18pt;
            font-weight: bold;
            text-transform: uppercase;
            margin: 0;
        }

        .header-subtitle {
            font-size: 14pt;
            margin: 5px 0 0 0;
        }

        .meta-info {
            margin-bottom: 20px;
            font-size: 10pt;
        }

        .meta-info table {
            width: 100%;
            border: none;
        }

        .meta-info td {
            padding: 3px 0;
            border: none !important;
        }

        .report-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 30px;
            font-size: 10pt;
        }

        .report-table th, .report-table td {
            border: 1px solid black !important;
            padding: 8px 10px;
            text-align: left;
        }

        .report-table th {
            background-color: #f2f2f2 !important;
            font-weight: bold;
            text-transform: uppercase;
        }

        .footer-container {
            margin-top: 40px;
            border-top: 1px solid black;
            padding-top: 10px;
            font-size: 9pt;
            text-align: center;
        }

        @media print {
            body {
                padding: 0;
            }
            .no-print {
                display: none !important;
            }
        }
    </style>
</head>
<body>

    <div class="no-print mb-4 d-flex justify-content-end">
        <button onclick="window.print()" class="btn btn-primary px-4 me-2">
            Print Now
        </button>
        <button onclick="window.close()" class="btn btn-secondary px-4">
            Close Window
        </button>
    </div>

    <!-- Library Header -->
    <div class="header-container">
        <h1 class="header-title">UB Library</h1>
        <div class="header-subtitle">Library Management System</div>
        <h3 class="fw-bold mt-3 mb-0" style="font-size: 14pt;">LAPORAN PEMINJAMAN BUKU</h3>
    </div>

    <!-- Report Info -->
    <div class="meta-info">
        <table>
            <tr>
                <td style="width: 20%;"><strong>Generated Date:</strong></td>
                <td>{{ now()->translatedFormat('d F Y H:i') }}</td>
                <td style="width: 20%; text-align: right;"><strong>Generated By:</strong></td>
                <td style="text-align: right;">{{ $generatedBy }}</td>
            </tr>
            <tr>
                <td><strong>Selected Date Range:</strong></td>
                <td>{{ $dateRange }}</td>
                <td style="text-align: right;"><strong>Total Records:</strong></td>
                <td style="text-align: right;">{{ $records->count() }}</td>
            </tr>
        </table>
    </div>

    <!-- Report Table -->
    <table class="report-table">
        <thead>
            <tr>
                <th style="width: 5%;">No.</th>
                <th style="width: 30%;">Book Title</th>
                <th style="width: 20%;">Member</th>
                <th style="width: 12%;">Borrow Date</th>
                <th style="width: 12%;">Due Date</th>
                <th style="width: 12%;">Return Date</th>
                <th style="width: 9%;">Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($records as $index => $record)
                @php
                    $member = \App\Models\Member::where('email', $record->user->email)->first();
                @endphp
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td><strong>{{ $record->book->judul ?? 'Buku Dihapus' }}</strong></td>
                    <td>{{ $record->user->name ?? 'User' }} ({{ $member->kode_anggota ?? '-' }})</td>
                    <td>{{ \Carbon\Carbon::parse($record->borrow_date)->translatedFormat('d M Y') }}</td>
                    <td>{{ \Carbon\Carbon::parse($record->due_date)->translatedFormat('d M Y') }}</td>
                    <td>
                        @if($record->return_date)
                            {{ \Carbon\Carbon::parse($record->return_date)->translatedFormat('d M Y') }}
                        @else
                            -
                        @endif
                    </td>
                    <td>
                        {{ $record->displayStatus() }}
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <!-- Footer -->
    <div class="footer-container">
        <p class="mb-1">Total Records: {{ $records->count() }} | Generated automatically by UB Library System</p>
    </div>

    <!-- Auto Print Script -->
    <script>
        window.addEventListener('load', function() {
            setTimeout(function() {
                window.print();
            }, 500);
        });
    </script>
</body>
</html>
